const STORE='ete_diagnostico_v9';
let state={students:[],questions:[],map:{},descriptors:[],history:[],meta:{updated:null}};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function save(){state.meta.updated=new Date().toLocaleString('pt-BR');localStorage.setItem(STORE,JSON.stringify(state));$('#lastSave').textContent='Último salvamento: '+state.meta.updated;}
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem(STORE)||'{}'))}catch(e){} if(state.meta?.updated)$('#lastSave').textContent='Último salvamento: '+state.meta.updated;}
async function loadDescriptors(){try{let [p,m]=await Promise.all([fetch('descritores/portugues-em.json').then(r=>r.json()),fetch('descritores/matematica-em.json').then(r=>r.json())]);state.descriptors=[...p,...m];}catch(e){state.descriptors=[]} renderDescriptors();}
function pct(n,d){return d?Math.round(n/d*100):0} function level(v){return v>=70?['Consolidado','ok','🟢']:v>=40?['Em desenvolvimento','warn','🟡']:['Crítico','bad','🔴']}
function parseData(text){let lines=text.trim().split(/\r?\n/).filter(Boolean); if(!lines.length)return; let sep=lines[0].includes(';')?';':','; let head=lines[0].split(sep).map(x=>x.trim()); let qs=head.slice(1).map((h,i)=>h||`Q${i+1}`); let students=lines.slice(1,51).map(l=>{let cols=l.split(sep).map(x=>x.trim());return {name:cols[0]||'Aluno sem nome',answers:qs.map((q,i)=>String(cols[i+1]||'0').match(/1|s|sim|certo|acerto/i)?1:0)}}).filter(s=>s.name); state.questions=qs; state.students=students; qs.forEach(q=>state.map[q]=state.map[q]||''); save(); renderAll(); go('turma');}
function calcStudent(s){let total=s.answers.length, ac=s.answers.reduce((a,b)=>a+b,0), p=pct(ac,total);let crit=[];s.answers.forEach((v,i)=>{if(!v&&state.map[state.questions[i]])crit.push(state.map[state.questions[i]])});return {total,ac,p,crit:[...new Set(crit)]}}
function descriptorStats(){let out={};state.questions.forEach((q,i)=>{let d=state.map[q]||'Sem descritor'; if(!out[d])out[d]={d,total:0,ac:0,qs:[]}; out[d].total+=state.students.length; out[d].ac+=state.students.reduce((a,s)=>a+(s.answers[i]||0),0); out[d].qs.push(q)}); return Object.values(out).map(x=>({...x,p:pct(x.ac,x.total)})).sort((a,b)=>a.p-b.p)}
function renderSummary(){let n=state.students.length, q=state.questions.length;let acc=state.students.reduce((a,s)=>a+calcStudent(s).ac,0), total=n*q, p=pct(acc,total);let prior=state.students.filter(s=>calcStudent(s).p<40).length;let crit=descriptorStats().filter(d=>d.p<40&&d.d!='Sem descritor').length;$('#summaryCards').innerHTML=[['👨‍🎓','Alunos avaliados',n],['📋','Questões',q],['📊','Média geral',p+'%'],['🔴','Alunos prioritários',prior],['🧩','Descritores críticos',crit]].map(c=>`<div class="card"><span>${c[0]} ${c[1]}</span><b>${c[2]}</b></div>`).join('')}
function renderMap(){let el=$('#questionMap'); if(!el)return; el.innerHTML=state.questions.map(q=>`<label>${q}<select data-q="${q}"><option value="">Selecionar descritor</option>${state.descriptors.map(d=>`<option ${state.map[q]==d.codigo?'selected':''} value="${d.codigo}">${d.codigo} - ${d.disciplina}</option>`).join('')}</select></label>`).join(''); $$('[data-q]').forEach(x=>x.onchange=()=>{state.map[x.dataset.q]=x.value;save();renderAll()})}
function renderStudents(){let list=$('#studentList'); if(!list)return; let term=($('#studentSearch')?.value||'').toLowerCase(); list.innerHTML=state.students.filter(s=>s.name.toLowerCase().includes(term)).map((s,i)=>{let c=calcStudent(s), l=level(c.p);return `<button data-st="${i}">${l[2]} ${s.name}<br><small>${c.p}% • ${l[0]}</small></button>`}).join('')||'<p class="hint">Nenhum aluno importado.</p>'; $$('[data-st]').forEach(b=>b.onclick=()=>showStudent(+b.dataset.st));}
function showStudent(i){let s=state.students[i], c=calcStudent(s), l=level(c.p);let desc=c.crit.map(code=>state.descriptors.find(d=>d.codigo==code)).filter(Boolean);$('#studentDetail').innerHTML=`<h3>${s.name}</h3><p><span class="badge ${l[1]}">${l[2]} ${l[0]}</span></p><div class="metricgrid"><div class="card"><span>Acertos</span><b>${c.ac}/${c.total}</b></div><div class="card"><span>Percentual</span><b>${c.p}%</b></div><div class="card"><span>Descritores críticos</span><b>${c.crit.length}</b></div></div><h4>Feedback individual</h4><div class="reportbox">${studentFeedback(s)}</div><h4>Descritores para intervenção</h4>${desc.map(d=>`<details open><summary>${d.codigo} — ${d.texto}</summary><p>${d.explicacao}</p><p><b>Intervenção:</b> ${d.intervencao}</p></details>`).join('')||'<p class="hint">Sem descritores críticos mapeados.</p>'}`}
function studentFeedback(s){let c=calcStudent(s), l=level(c.p);let d=c.crit.slice(0,4).join(', ')||'sem descritor crítico mapeado';return `${s.name} apresentou desempenho ${l[0].toLowerCase()}, com ${c.ac} acertos em ${c.total} questões (${c.p}%). Os descritores que merecem maior atenção são: ${d}. Recomenda-se acompanhamento individualizado, retomada dos conteúdos associados aos erros e nova verificação após intervenção curta.`}
function renderClass(){let el=$('#classReport'); if(!el)return;let stats=descriptorStats(), n=state.students.length,q=state.questions.length;let p=pct(state.students.reduce((a,s)=>a+calcStudent(s).ac,0),n*q);let l=level(p);let qs=state.questions.map((q,i)=>({q,p:pct(state.students.reduce((a,s)=>a+(s.answers[i]||0),0),n)})).sort((a,b)=>a.p-b.p);el.innerHTML=`<div class="cards"><div class="card"><span>Resultado da turma</span><b>${p}%</b><span class="badge ${l[1]}">${l[2]} ${l[0]}</span></div><div class="card"><span>Prioritários</span><b>${state.students.filter(s=>calcStudent(s).p<40).length}</b></div><div class="card"><span>Em desenvolvimento</span><b>${state.students.filter(s=>{let p=calcStudent(s).p;return p>=40&&p<70}).length}</b></div><div class="card"><span>Consolidados</span><b>${state.students.filter(s=>calcStudent(s).p>=70).length}</b></div><div class="card"><span>Itens críticos</span><b>${qs.filter(x=>x.p<40).length}</b></div></div><div class="panel"><h3>Descritores críticos</h3>${stats.slice(0,8).map(d=>`<p><b>${d.d}</b>: ${d.p}% de acertos (${d.qs.join(', ')})</p>`).join('')||'<p class="hint">Mapeie descritores para análise.</p>'}</div>`;renderHeatmap();}
function renderHeatmap(){let el=$('#heatmap'); if(!el)return; el.innerHTML=state.students.map(s=>`<div class="heatrow"><span class="heatname">${s.name}</span>${s.answers.map(v=>`<span class="cell c${v}"></span>`).join('')}</div>`).join('')||'<p class="hint">Importe dados para exibir o mapa.</p>'}
function renderDescriptors(){let el=$('#descriptorList'); if(!el)return;let disc=$('#descriptorDiscipline')?.value||'todos', term=($('#descriptorSearch')?.value||'').toLowerCase();let arr=state.descriptors.filter(d=>(disc=='todos'||d.disciplina==disc)&&(`${d.codigo} ${d.texto} ${d.explicacao}`.toLowerCase().includes(term)));el.innerHTML=arr.map(d=>`<details class="desc"><summary>${d.disciplina} • ${d.codigo} — ${d.texto}</summary><p><b>O que avalia:</b> ${d.explicacao}</p><p><b>Intervenção sugerida:</b> ${d.intervencao}</p><p><b>BNCC:</b> ${d.bncc}</p><p><b>Exemplos:</b> ${d.exemplos.join(' | ')}</p></details>`).join('')||'<p class="hint">Nenhum descritor encontrado.</p>'}
function renderTomorrow(){let crit=descriptorStats().filter(d=>d.d!='Sem descritor').slice(0,3), el=$('#tomorrowPlan'); if(!el)return; el.innerHTML=crit.length?`<h3>Prioridades para a próxima aula</h3>${crit.map((d,i)=>{let info=state.descriptors.find(x=>x.codigo==d.d);return `<p><b>${i+1}. ${d.d} — ${d.p}% de acertos.</b><br>${info?info.texto:''}<br><b>Ação:</b> ${info?info.intervencao:'Retomar habilidade com atividade curta e correção comentada.'}</p>`}).join('')}<p><b>Estratégia:</b> 15 min de retomada, 25 min de prática guiada, 20 min de atividade em pares e 10 min de verificação rápida.</p>`:'<p class="hint">Mapeie os descritores para gerar o plano.</p>'}
function renderHistory(){let el=$('#history'); if(!el)return; el.innerHTML=state.history.map((h,i)=>`<div class="panel"><b>${h.date}</b><p>Média: ${h.avg}% • Alunos: ${h.students}</p></div>`).join('')||'<p class="hint">Nenhum diagnóstico salvo.</p>'}
function makeReport(type){let avg=pct(state.students.reduce((a,s)=>a+calcStudent(s).ac,0),state.students.length*state.questions.length);let crit=descriptorStats().slice(0,5).map(d=>`${d.d} (${d.p}%)`).join(', '); if(type=='familia')return state.students.map(studentFeedback).join('\n\n'); if(type=='conselho')return `CONSELHO DE CLASSE\nA turma apresentou média geral de ${avg}%. Alunos prioritários: ${state.students.filter(s=>calcStudent(s).p<40).length}. Descritores que exigem intervenção: ${crit}. Recomenda-se retomada direcionada e acompanhamento dos estudantes com baixo desempenho.`; if(type=='coordenacao')return `RELATÓRIO PARA COORDENAÇÃO\nAlunos avaliados: ${state.students.length}\nQuestões: ${state.questions.length}\nMédia geral: ${avg}%\nDescritores críticos: ${crit}\nEncaminhamento: organizar agrupamentos por dificuldade e nova avaliação curta após intervenção.`; return `RELATÓRIO DA TURMA\nMédia geral: ${avg}%\nDescritores críticos: ${crit}\nPlano: priorizar os descritores de menor acerto, com atividades curtas, correção comentada e reavaliação.`}
function renderAll(){renderSummary();renderMap();renderStudents();renderClass();renderDescriptors();renderTomorrow();renderHistory();}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id==id));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view==id));renderAll();}
document.addEventListener('click',e=>{let goid=e.target.dataset.go||e.target.dataset.view;if(goid)go(goid); if(e.target.dataset.report)$('#reportOutput').value=makeReport(e.target.dataset.report)});
$('#processData').onclick=()=>parseData($('#pasteData').value);$('#loadExample').onclick=()=>{$('#pasteData').value='Aluno,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8\nAna,1,1,0,1,0,1,1,0\nBruno,0,1,0,0,0,1,0,0\nCarla,1,1,1,1,1,0,1,1\nDiego,0,0,1,0,1,0,0,1';parseData($('#pasteData').value)};
$('#fileInput').onchange=e=>{let f=e.target.files[0]; if(!f)return; let r=new FileReader(); r.onload=()=>{$('#pasteData').value=r.result; if(/csv|text/.test(f.type)||f.name.match(/\.csv|\.txt$/i))parseData(r.result)}; r.readAsText(f)};
$('#studentSearch').oninput=renderStudents; $('#descriptorSearch').oninput=renderDescriptors; $('#descriptorDiscipline').onchange=renderDescriptors;
$('#saveSnapshot').onclick=()=>{let avg=pct(state.students.reduce((a,s)=>a+calcStudent(s).ac,0),state.students.length*state.questions.length);state.history.push({date:new Date().toLocaleString('pt-BR'),avg,students:state.students.length});save();renderHistory()};
$('#clearSnapshots').onclick=()=>{if(confirm('Limpar histórico?')){state.history=[];save();renderHistory()}};
$('#clearAll').onclick=()=>{if(confirm('Apagar todos os dados salvos?')){localStorage.removeItem(STORE);location.reload()}};
$('#exportJson').onclick=()=>download('backup-diagnostico-ete.json',JSON.stringify(state,null,2));
$('#importJson').onchange=e=>{let f=e.target.files[0]; if(!f)return; let r=new FileReader(); r.onload=()=>{state=JSON.parse(r.result);save();renderAll()}; r.readAsText(f)};
$('#copyReport').onclick=()=>navigator.clipboard.writeText($('#reportOutput').value||'');$('#downloadReport').onclick=()=>download('relatorio-diagnostico.txt',$('#reportOutput').value||'');
function download(name,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
load();loadDescriptors().then(renderAll);
