(function(){
 const A=()=>window.ETE;
 function compute(assessment){
  const q=assessment.questions||[], desc=assessment.descriptors||[], key=assessment.key||[], students=assessment.students||[];
  const itemCorrect=Array(q.length).fill(0), descMap={};
  const results=students.map((s,idx)=>{const answers=s.answers||[];const correct=answers.map((v,i)=>A().letter(v)&&A().letter(v)===A().letter(key[i])?1:0);const total=correct.reduce((a,b)=>a+b,0);correct.forEach((c,i)=>{itemCorrect[i]+=c; const d=desc[i]||'Sem descritor'; (descMap[d]??={descritor:d,total:0,correct:0,students:[]}); descMap[d].total++; descMap[d].correct+=c; if(!c) descMap[d].students.push(s.name);});return {...s,index:idx,correct,total,percent:A().pct(total,q.length),level:total/q.length>=.7?'Consolidado':total/q.length>=.4?'Em desenvolvimento':'Prioritário'};});
  const items=q.map((name,i)=>({index:i,question:name||'Q'+(i+1),descriptor:desc[i]||'',key:key[i]||'',correct:itemCorrect[i],percent:A().pct(itemCorrect[i],students.length)}));
  const descriptorStats=Object.values(descMap).map(d=>({...d,percent:A().pct(d.correct,d.total),students:[...new Set(d.students)]})).sort((a,b)=>a.percent-b.percent);
  return {students:results,items,descriptorStats,summary:{nStudents:students.length,nQuestions:q.length,avg:A().pct(results.reduce((a,s)=>a+s.total,0),students.length*q.length),priority:results.filter(s=>s.level==='Prioritário').length}};
 }
 function render(){renderSummary();renderClassReport();renderHeatmap();renderStudents();renderTomorrow();A().renderSelects();A().renderWizard?.();}
 function renderSummary(){const r=compute(A().state.assessment);const box=A().$('#summaryCards'); if(!box)return; box.innerHTML=`<div class="card"><span>Alunos</span><b>${r.summary.nStudents}</b></div><div class="card"><span>Questões</span><b>${r.summary.nQuestions}</b></div><div class="card"><span>Média</span><b>${r.summary.avg}%</b></div><div class="card"><span>Prioritários</span><b>${r.summary.priority}</b></div><div class="card"><span>Descritores críticos</span><b>${r.descriptorStats.filter(d=>d.percent<40).length}</b></div>`;}
 function renderClassReport(){const r=compute(A().state.assessment);const box=A().$('#classReport'); if(!box)return; const valid=A().isAssessmentValid?.(); if(valid&&!valid.ok&&A().state.assessment.questions?.length){box.innerHTML='<div class="panel statusbox status-error"><b>Análise bloqueada pela validação.</b><p>Volte à Importação e corrija: '+A().safe(valid.issues.join(', '))+'.</p></div>';return;} if(!r.summary.nStudents){box.innerHTML='<div class="panel empty">Importe uma avaliação para gerar o diagnóstico.</div>';return;} const crit=r.descriptorStats.slice(0,5).map(d=>`<li><b>${d.descritor}</b> — ${d.percent}% de aproveitamento</li>`).join(''); box.innerHTML=`<div class="cards"><div class="card"><span>Média geral</span><b>${r.summary.avg}%</b></div><div class="card"><span>Consolidado</span><b>${r.students.filter(s=>s.level==='Consolidado').length}</b></div><div class="card"><span>Em desenvolvimento</span><b>${r.students.filter(s=>s.level==='Em desenvolvimento').length}</b></div><div class="card"><span>Prioritário</span><b>${r.summary.priority}</b></div><div class="card"><span>Disciplina</span><b style="font-size:18px">${A().safe(A().state.assessment.discipline)}</b></div></div><div class="panel"><h3>Descritores mais críticos</h3><ol>${crit}</ol></div>`;}
 function renderHeatmap(){const r=compute(A().state.assessment);const box=A().$('#heatmap'); if(!box)return; box.innerHTML=r.students.map(s=>`<div class="heatrow"><span class="heatname">${A().safe(s.name)}</span>${s.correct.map(c=>`<span class="cell c${c}"></span>`).join('')}</div>`).join('')||'<p class="hint">Sem dados.</p>';}
 function renderStudents(){const r=compute(A().state.assessment);const list=A().$('#studentList'); if(!list)return; const term=A().norm(A().$('#studentSearch')?.value).toLowerCase(); const rows=r.students.filter(s=>!term||s.name.toLowerCase().includes(term)); list.innerHTML=rows.map(s=>`<button data-student="${s.index}"><b>${A().safe(s.name)}</b><br><span class="badge ${s.level==='Prioritário'?'bad':s.level==='Consolidado'?'ok':'warn'}">${s.level}</span> ${s.total}/${r.summary.nQuestions} (${s.percent}%)</button>`).join('')||'<p class="hint">Nenhum aluno.</p>'; list.querySelectorAll('button').forEach(b=>b.onclick=()=>renderStudentDetail(Number(b.dataset.student)));}
 function renderStudentDetail(i){const r=compute(A().state.assessment);const s=r.students.find(x=>x.index===i);const box=A().$('#studentDetail'); if(!s||!box)return; const weak={}; s.correct.forEach((c,k)=>{if(!c){const d=A().state.assessment.descriptors[k]||'Sem descritor';weak[d]=(weak[d]||0)+1;}}); const weakList=Object.entries(weak).sort((a,b)=>b[1]-a[1]); box.innerHTML=`<h3>${A().safe(s.name)}</h3><p><span class="badge ${s.level==='Prioritário'?'bad':s.level==='Consolidado'?'ok':'warn'}">${s.level}</span></p><p><b>Acertos:</b> ${s.total}/${r.summary.nQuestions} (${s.percent}%)</p><h4>Descritores prioritários</h4><ul>${weakList.slice(0,5).map(([d,n])=>`<li>${A().safe(d)} — ${n} erro(s)</li>`).join('')||'<li>Nenhum descritor crítico.</li>'}</ul><div class="actions"><button onclick="ETE.showView('recuperacao');document.querySelector('#mapStudent').value='${i}';document.querySelector('#sheetStudent').value='${i}'">Gerar recuperação</button></div>`;}
 function renderTomorrow(){const r=compute(A().state.assessment);const box=A().$('#tomorrowPlan'); if(!box)return; const top=r.descriptorStats.slice(0,3); box.innerHTML=top.length?`<ol>${top.map((d,i)=>`<li><b>Prioridade ${i+1}: ${A().safe(d.descritor)}</b> — ${d.percent}% de aproveitamento. Retomar conceito, resolver itens guiados e aplicar atividade curta de verificação.</li>`).join('')}</ol>`:'<p class="hint">Importe dados para gerar prioridade.</p>';}
 window.Diagnostico={compute,render,renderStudents,renderStudentDetail};
})();
