(function(){
 const A=()=>window.ETE;
 function buildGrid(vals=[]){const box=A().$('#photoKeyGrid');if(!box)return;box.innerHTML=Array.from({length:26},(_,i)=>`<div class="photo-q"><label>Q${i+1}</label><select>${['','A','B','C','D','E'].map(v=>`<option ${vals[i]===v?'selected':''}>${v}</option>`).join('')}</select></div>`).join('');}
 function readGrid(){return Array.from(document.querySelectorAll('#photoKeyGrid select')).map(s=>A().letter(s.value));}
 function extract(text){const byNum=Array(26).fill('');const clean=String(text||'').toUpperCase().replace(/[|]/g,'1');const re=/(?:Q\s*)?(\d{1,2})\s*[:\-\.)]?\s*([A-E])/gi;let m;while((m=re.exec(clean))){const n=+m[1];if(n>=1&&n<=26)byNum[n-1]=m[2].toUpperCase();}if(byNum.filter(Boolean).length>=8)return byNum;const seq=(clean.match(/\b[A-E]\b/g)||[]).map(x=>x.toUpperCase());return Array.from({length:26},(_,i)=>seq[i]||byNum[i]||'');}
 function preprocess(file){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const max=1400;const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);const data=ctx.getImageData(0,0,c.width,c.height);for(let i=0;i<data.data.length;i+=4){let g=.299*data.data[i]+.587*data.data[i+1]+.114*data.data[i+2];g=g>150?255:0;data.data[i]=data.data[i+1]=data.data[i+2]=g;}ctx.putImageData(data,0,0);c.toBlob(b=>resolve(b||file),'image/png');};img.onerror=reject;img.src=URL.createObjectURL(file);});}
 async function readPhoto(){try{const file=A().$('#photoKeyInput').files[0];if(!file)throw new Error('Selecione uma foto.');A().status('#photoKeyStatus','Preparando imagem e lendo por OCR. Use apenas gabarito oficial ou cartão individual. Aguarde...','work');const url=URL.createObjectURL(file);const img=A().$('#photoPreview');img.src=url;A().$('#photoPreviewWrap').style.display='block'; if(!window.Tesseract)throw new Error('OCR não carregou. Verifique a internet ou digite manualmente.');const processed=await preprocess(file);const out=await Tesseract.recognize(processed,'eng+por');const vals=extract(out.data.text||'');buildGrid(vals);const n=vals.filter(Boolean).length;A().status('#photoKeyStatus',`OCR concluído com ${n}/26 respostas encontradas. Confira manualmente antes de salvar.`,n>=20?'ok':'work');}catch(e){A().status('#photoKeyStatus',A().safe(e.message),'error');}}
 function saveRecord(){const type=A().$('#photoRecordType').value;const name=type==='key'?'Gabarito':(A().norm(A().$('#photoStudentName').value)||'Aluno sem nome');const answers=readGrid();if(answers.filter(Boolean).length<1)return alert('Preencha ou leia as alternativas antes de salvar.');if(answers.filter(Boolean).length<26&&!confirm('Há menos de 26 respostas preenchidas. Deseja salvar mesmo assim?'))return;const rec={id:A().uid(),type,name,answers,date:new Date().toLocaleString('pt-BR')}; if(type==='key')A().state.photoRecords=A().state.photoRecords.filter(r=>r.type!=='key');A().state.photoRecords.push(rec);A().save();renderRecords();A().status('#photoKeyStatus','Registro salvo após conferência.','ok');}
 function renderRecords(){const box=A().$('#photoSavedList');if(!box)return;const rows=A().state.photoRecords||[];box.innerHTML=rows.length?rows.map(r=>`<div class="saved-row"><div><b>${A().safe(r.name)}</b><br><small>${A().safe(r.type)} • ${A().safe(r.date)} • ${r.answers.filter(Boolean).length}/26 respostas</small></div><button class="secondary smallBtn" data-delphoto="${r.id}">remover</button></div>`).join(''):'<p class="hint">Nenhum registro salvo.</p>';box.querySelectorAll('[data-delphoto]').forEach(b=>b.onclick=()=>{A().state.photoRecords=A().state.photoRecords.filter(r=>r.id!==b.dataset.delphoto);A().save();renderRecords();});}
 function apply(){const key=A().state.photoRecords.find(r=>r.type==='key');const students=A().state.photoRecords.filter(r=>r.type==='student').map(r=>({name:r.name,answers:r.answers}));const questions=Array.from({length:26},(_,i)=>'Q'+(i+1));const descriptors=A().state.assessment.descriptors.length===26?A().state.assessment.descriptors:Array.from({length:26},(_,i)=>'D'+((i%20)+1));A().setAssessment({questions,descriptors,key:key?key.answers:A().state.assessment.key,students:students.length?students:A().state.assessment.students});A().status('#photoKeyStatus','Registros aplicados à avaliação atual. Confira os descritores antes de analisar.','ok');}
 function exportModel(){const a=A().state.assessment;const rows=[['Aluno',...Array.from({length:26},(_,i)=>'Q'+(i+1))],['Descritores',...(a.descriptors.length===26?a.descriptors:Array.from({length:26},(_,i)=>'D'+((i%20)+1)))],['Gabarito',...(a.key.length===26?a.key:(A().state.photoRecords.find(r=>r.type==='key')?.answers||[]))],...A().state.photoRecords.filter(r=>r.type==='student').map(r=>[r.name,...r.answers])];A().download('modelo-gabaritos.xls',A().toTSV(rows),'application/vnd.ms-excel;charset=utf-8');}
 function bind(){buildGrid();renderRecords();A().$('#readPhotoKey')&&(A().$('#readPhotoKey').onclick=readPhoto);A().$('#savePhotoKey')&&(A().$('#savePhotoKey').onclick=saveRecord);A().$('#clearPhotoGrid')&&(A().$('#clearPhotoGrid').onclick=()=>buildGrid());A().$('#applyPhotoKey')&&(A().$('#applyPhotoKey').onclick=apply);A().$('#exportPhotoModel')&&(A().$('#exportPhotoModel').onclick=exportModel);A().$('#exportPhotoPdf')&&(A().$('#exportPhotoPdf').onclick=()=>window.Exportacao?.printReport(A().toTSV([['Aluno',...Array.from({length:26},(_,i)=>'Q'+(i+1))],...A().state.photoRecords.map(r=>[r.name,...r.answers])]),'Registros por foto'));}
 window.OCR={buildGrid,readPhoto,saveRecord,renderRecords,extract,preprocess};document.addEventListener('DOMContentLoaded',bind);
})();
