(function(){
 const A=()=>window.ETE;
 function baseHeader(title){const a=A().state.assessment;return `${title}\nETE Professor José Luiz de Mendonça\nTítulo: ${a.title||'Avaliação atual'}\nTurma: ${a.turma||'Não informada'}\nDisciplina: ${a.discipline}\nTipo: ${a.tipo||'não informado'}\nData da avaliação: ${a.date||'não informada'}\nGerado em: ${new Date().toLocaleString('pt-BR')}\n\n`;}
 function weakByStudent(s){const out={};s.correct.forEach((c,i)=>{if(!c){const d=A().state.assessment.descriptors[i]||'Sem descritor';out[d]=(out[d]||0)+1;}});return Object.entries(out).sort((a,b)=>b[1]-a[1]);}
 function turma(){const r=A().getResults();return baseHeader('RELATÓRIO DA TURMA')+`Alunos avaliados: ${r.summary.nStudents}\nQuestões: ${r.summary.nQuestions}\nMédia geral: ${r.summary.avg}%\nAlunos prioritários: ${r.summary.priority}\n\nDistribuição:\n- Consolidado: ${r.students.filter(s=>s.level==='Consolidado').length}\n- Em desenvolvimento: ${r.students.filter(s=>s.level==='Em desenvolvimento').length}\n- Prioritário: ${r.students.filter(s=>s.level==='Prioritário').length}\n\nDescritores críticos:\n`+r.descriptorStats.slice(0,10).map(d=>`- ${d.descritor}: ${d.percent}% (${d.students.length} aluno(s) com dificuldade)`).join('\n')+`\n\nQuestões com menor desempenho:\n`+r.items.sort((a,b)=>a.percent-b.percent).slice(0,8).map(it=>`- ${it.question} (${it.descriptor}): ${it.percent}%`).join('\n')+`\n\nEncaminhamento coletivo:\nPriorizar os três descritores de menor aproveitamento, iniciar com correção comentada, depois atividade guiada e nova verificação curta.`;}
 function familia(){const r=A().getResults();return baseHeader('RELATÓRIO PARA FAMÍLIA')+r.students.map(s=>{const w=weakByStudent(s).slice(0,3).map(x=>x[0]).join(', ')||'sem dificuldade prioritária';return `${s.name}\nDesempenho: ${s.percent}% — ${s.level}.\nPontos que precisam de atenção: ${w}.\nOrientação: manter rotina semanal de estudo, revisar os conteúdos indicados e realizar exercícios curtos com correção.`;}).join('\n\n');}
 function conselho(){const r=A().getResults();return baseHeader('RELATÓRIO PARA CONSELHO DE CLASSE')+`Panorama: média ${r.summary.avg}%, ${r.summary.priority} aluno(s) em situação prioritária.\n\nAlunos prioritários:\n`+r.students.filter(s=>s.level==='Prioritário').map(s=>`- ${s.name}: ${s.percent}% | descritores: ${weakByStudent(s).slice(0,3).map(x=>x[0]).join(', ')}`).join('\n')+`\n\nIntervenção sugerida:\nOrganizar grupos por descritores críticos, aplicar recuperação paralela de 4 semanas e acompanhar evolução em novo simulado.`;}
 function coordenacao(){const r=A().getResults();return baseHeader('RELATÓRIO DA COORDENAÇÃO')+`Indicadores gerais: ${r.summary.nStudents} alunos, média ${r.summary.avg}%, ${r.descriptorStats.filter(d=>d.percent<40).length} descritores críticos.\n\nDescritores críticos da escola/turma:\n`+r.descriptorStats.slice(0,8).map((d,i)=>`${i+1}. ${d.descritor} — ${d.percent}% — ${d.students.length} aluno(s)`).join('\n')+`\n\nAlunos prioritários:\n`+r.students.filter(s=>s.level==='Prioritário').slice(0,20).map(s=>`- ${s.name}: ${s.percent}%`).join('\n')+`\n\nEvolução geral registrada:\n`+(A().state.snapshots||[]).map(s=>`- ${s.name}: média ${s.avg}% (${s.date})`).join('\n');}
 function individual(idx=0){const r=A().getResults();const s=r.students[idx]||r.students[0];if(!s)return baseHeader('RELATÓRIO INDIVIDUAL')+'Nenhum aluno carregado.';const weak=weakByStudent(s);const coh=window.TRI?.coherence(r,s);return baseHeader('RELATÓRIO INDIVIDUAL')+`Aluno: ${s.name}\nDesempenho: ${s.total}/${r.summary.nQuestions} (${s.percent}%)\nStatus: ${s.level}\nÍndice de coerência: ${coh?coh.score+'/100 — '+coh.label:'não calculado'}\n\nDescritores prioritários:\n`+weak.map(([d,n])=>`- ${d}: ${n} erro(s)`).join('\n')+`\n\nPlano imediato:\n1. Retomar os descritores com mais erros.\n2. Resolver exemplos guiados.\n3. Aplicar lista individualizada.\n4. Conferir evolução na próxima avaliação.`;}
 function build(type){if(type==='familia')return familia(); if(type==='conselho')return conselho(); if(type==='coordenacao')return coordenacao(); if(type==='individual'){const idx=Number(A().$('#reportStudent')?.value||0);return individual(idx);} return turma();}

 function compareDisciplines(){
  const snaps=A().state.snapshots||[];
  const groups={};
  snaps.forEach(s=>{const turma=s.turma||'Turma não informada'; const disc=s.discipline||'Disciplina não informada'; (groups[turma]??={}); (groups[turma][disc]??=[]).push(Number(s.avg)||0);});
  return Object.entries(groups).map(([turma,byDisc])=>{const lp=byDisc['Língua Portuguesa']||[]; const mat=byDisc['Matemática']||[]; const avg=arr=>arr.length?Math.round(arr.reduce((a,b)=>a+b,0)/arr.length*10)/10:null; return {turma,lp:avg(lp),mat:avg(mat),nLP:lp.length,nMat:mat.length,diff:(avg(lp)!=null&&avg(mat)!=null)?Math.round((avg(lp)-avg(mat))*10)/10:null};});
 }
 function renderComparison(){
  const box=A().$('#disciplineComparison'); if(!box)return; const rows=compareDisciplines();
  if(!rows.length){box.innerHTML='<h3>Comparação Português × Matemática</h3><p class="hint">Salve avaliações no histórico para comparar as disciplinas por turma. Exemplo: Diagnóstica de Português e Diagnóstica de Matemática da mesma turma.</p>';return;}
  box.innerHTML='<h3>Comparação Português × Matemática</h3><p class="hint">A comparação usa avaliações salvas no histórico local. Para uma leitura institucional completa, salve avaliações de ambas as disciplinas para cada turma.</p><div class="preview-table"><div class="preview-row"><span>Turma</span><span>Português</span><span>Matemática</span><span>Diferença LP-MAT</span><span>Registros LP</span><span>Registros MAT</span></div>'+rows.map(r=>`<div class="preview-row"><span><b>${A().safe(r.turma)}</b></span><span>${r.lp==null?'-':r.lp+'%'}</span><span>${r.mat==null?'-':r.mat+'%'}</span><span>${r.diff==null?'-':r.diff+' p.p.'}</span><span>${r.nLP}</span><span>${r.nMat}</span></div>`).join('')+'</div>';
 }
 function renderCoord(){const box=A().$('#coordDashboard');if(!box)return;const r=A().getResults();const a=A().state.assessment;const last=A().state.snapshots?.slice(-1)[0];const crit=r.descriptorStats.slice(0,5);const prior=r.students.filter(s=>s.level==='Prioritário').slice(0,12);const bank=(window.BancoQuestoes?.allBank?.()||[]).filter(q=>q.discipline===a.discipline).length;const weakTurma=(A().state.snapshots||[]).reduce((acc,s)=>{const t=s.turma||'Turma não informada';(acc[t]??=[]).push(s.avg||0);return acc;},{});const turmaCritica=Object.entries(weakTurma).map(([t,arr])=>({t,avg:Math.round(arr.reduce((a,b)=>a+b,0)/arr.length*10)/10,n:arr.length})).sort((a,b)=>a.avg-b.avg)[0];box.innerHTML=`<div class="cards"><div class="card"><span>Média</span><b>${r.summary.avg||0}%</b></div><div class="card"><span>Prioritários</span><b>${r.summary.priority||0}</b></div><div class="card"><span>Descritores críticos</span><b>${r.descriptorStats.filter(d=>d.percent<40).length}</b></div><div class="card"><span>Histórico</span><b>${A().state.snapshots.length}</b></div><div class="card"><span>Questões no banco</span><b>${bank}</b></div></div><div class="panel"><h3>Painel escolar da coordenação</h3><p><b>Avaliação atual:</b> ${A().safe(a.title||'Avaliação atual')} • ${A().safe(a.turma||'turma não informada')} • ${A().safe(a.discipline)}.</p><p><b>Situação atual:</b> média ${r.summary.avg||0}% com ${r.summary.priority||0} aluno(s) prioritário(s).</p><p><b>Turma crítica no histórico:</b> ${turmaCritica?A().safe(turmaCritica.t)+' • '+turmaCritica.avg+'% em '+turmaCritica.n+' registro(s)':'dados insuficientes.'}</p><p><b>Último registro histórico:</b> ${last?A().safe(last.name)+' • '+last.avg+'%':'nenhum registro salvo.'}</p><p><b>Prioridade gestora:</b> acompanhar descritores abaixo de 40%, garantir intervenção, cobrar nova avaliação após 4 semanas e comparar Português × Matemática por turma.</p></div><div class="grid2"><div class="panel"><h3>Descritores críticos</h3><ol>${crit.map(d=>`<li><b>${A().safe(d.descritor)}</b> — ${d.percent}% • ${d.students.length} aluno(s)</li>`).join('')||'<li>Sem dados.</li>'}</ol></div><div class="panel"><h3>Alunos prioritários</h3><ul>${prior.map(s=>`<li>${A().safe(s.name)} — ${s.percent}%</li>`).join('')||'<li>Nenhum aluno prioritário.</li>'}</ul></div></div>`;renderHistory();renderComparison();A().renderWizard?.();}
 function renderHistory(){const box=A().$('#history');if(!box)return;const snaps=A().state.snapshots||[];if(!snaps.length){box.innerHTML='<p class="hint">Nenhuma avaliação salva no histórico.</p>';return;} const max=Math.max(...snaps.map(s=>s.avg||0),100);box.innerHTML='<div class="history-chart">'+snaps.map(s=>`<div class="history-row"><b>${A().safe(s.name)}</b><div class="bar"><span style="width:${Math.max(3,(s.avg/max)*100)}%"></span></div><em>${s.avg}%</em><small>${A().safe(s.date)}</small></div>`).join('')+'</div>';}
 function bind(){document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{const txt=build(b.dataset.report);A().state.currentReport=txt;A().$('#reportOutput').value=txt;A().save();});A().$('#copyReport')&&(A().$('#copyReport').onclick=()=>navigator.clipboard?.writeText(A().$('#reportOutput').value||''));A().$('#downloadReport')&&(A().$('#downloadReport').onclick=()=>A().download('relatorio-ete.txt',A().$('#reportOutput').value||build('turma')));A().$('#exportReportPdf')&&(A().$('#exportReportPdf').onclick=()=>window.Exportacao?.printReport(A().$('#reportOutput').value||build('turma'),'Relatório ETE'));A().$('#saveSnapshot')&&(A().$('#saveSnapshot').onclick=()=>{const r=A().getResults();if(!r.summary.nStudents)return alert('Importe uma avaliação antes de salvar histórico.');const name=A().norm(A().$('#snapshotName').value)||'Avaliação '+(A().state.snapshots.length+1);A().state.snapshots.push({id:A().uid(),name,date:new Date().toLocaleString('pt-BR'),avg:r.summary.avg,students:r.summary.nStudents,critical:r.descriptorStats.slice(0,5),discipline:A().state.assessment.discipline,turma:A().state.assessment.turma||'',tipo:A().state.assessment.tipo||''});A().save();renderCoord();});A().$('#clearSnapshots')&&(A().$('#clearSnapshots').onclick=()=>{if(confirm('Limpar histórico?')){A().state.snapshots=[];A().save();renderCoord();}})}
 window.Relatorios={build,renderCoord,renderHistory,renderComparison,compareDisciplines,individual,turma,familia,conselho,coordenacao};document.addEventListener('DOMContentLoaded',bind);
})();
